### ISSUE TITLE
La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [castelnou/EstrD22s1#1]
La función `vieneDespues` definida no es la pedida. Por ejemplo, `Miercoles` viene después que `Lunes`, pero tu función no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by castelnou** [comment]
Se Crea una función que devuelva el número del dia de la semana, ej: Lunes = 1... Domingo = 7.
De esta manera ahora puedo preguntar por ">"

**Comment by fidel-ml** [comment]
Mejor. Ojo con los paréntesis...
