### ISSUE TITLE
Pr2: `esDelMismoRango` hace doble PM y tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [castelnou/EstrD22s1#12]
El doble PM debe estar justificado por el problema. Cuando no es así, es un abuso innecesario que muestra la falta de subtareas...

**Comment by castelnou** [comment]
Resuelto

**Comment by fidel-ml** [comment]
El cambio funciona para el ejercicio, pero NO es lo que te marqué. 
La idea no era cambiar la forma de resolver el otro ejercicio, sino entender cómo hacer LO MISMO, pero sin doble PM.
Ahora estás haciendo algo menos general que antes, y por eso esquivaste el problema. Pero no lo arreglaste. ¿Entendés el problema que tenías y cómo sacarlo?
