### ISSUE TITLE
Funciones and y or diferentes a las pedidas. 

### ISSUE THREAD

**Issue by fidel-ml** [castelnou/EstrD22s1#2]
La función `and` de la práctica 1 debería comportarse de la siguiente manera:
```
> and False (error "Mal")
False
```
Sin embargo, tu versión da `error "Mal"`.
Así, no es la función pedida.

Exactamente lo mismo pasa con la función `or`, que debería pasar el test `or True (error "Mal")` dando `True`.

**Comment by castelnou** [comment]
Arregle el Or (oBien) para que quede con menos pasos. 
En cuanto a lo comentado tanto para el or y and que no arroja el valor correcto, para esos casos mencionados, me dan el resultado correcto. Adjunto una prueba
![Captura](https://user-images.githubusercontent.com/3921128/163096699-86798fca-2cc4-4535-929d-10b4962097ec.JPG)

**Comment by fidel-ml** [comment]
En el `yTambien` faltan casos. El importante NO hacer doble PM a menos que sea imprescindible (y en este caso no lo es).

**Comment by castelnou** [comment]
Se dio solución al Issue.

**Comment by fidel-ml** [comment]
Seguís haciendo doble PM. No es adecuado mirar AMBOS parámetros, a menos que sea imprescindible...

**Comment by castelnou** [comment]
Se da solución para que solo se mire uno de los parámetros.
