### ISSUE TITLE
Pr3: `ramaMasLarga` no está hecha estrictamente por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [castelnou/EstrD22s1#25]
Al utilizar una función auxiliar sobre los subárboles, se pierde la idea de recursión estructural (y se trabaja de más).
Pensá por recursión estructural... (y subtareas)

**Comment by castelnou** [comment]
Arreglado

**Comment by fidel-ml** [comment]
No cambió nada.

**Comment by castelnou** [comment]
Arreglado los issues.
